import re
import json
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from pathlib import Path

app = FastAPI()

DATA_PATH = ""  # Set this to the path of your data file
PAGE_SIZE = 6 # Number of prompt groups per page (Equal to the number of answers generated by the same prompt)

BASE_DIR = Path(__file__).resolve().parent
templates = Jinja2Templates(directory=str(BASE_DIR / "templates"))
app.mount("/static", StaticFiles(directory=str(BASE_DIR / "static")), name="static")

def extract_data(file_path):
    data = []
    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                output = entry.get("output", "")
                rationale_match = re.search(r"<rationale>(.*?)</rationale>", output, re.DOTALL)
                problem_match = re.search(r"<problem>(.*?)</problem>", output, re.DOTALL)
                entry["rationale"] = rationale_match.group(1).strip() if rationale_match else "-1"
                entry["problem"] = problem_match.group(1).strip() if problem_match else "-1"
                entry["problem"] = re.sub(r"\\\((.*?)\\\)", lambda m: f"${m.group(1)}$", entry["problem"])
                entry["problem"] = re.sub(r"\\\[(.*?)\\\]", lambda m: f"$${m.group(1)}$$", entry["problem"])
                entry["r_format"] = entry.get("r_format", "-1")
                entry["avg_cot_len"] = entry.get("avg_cot_len", -1)
                entry["r_cot_len"] = entry.get("r_cot_len", -1)
                data.append(entry)
            except json.JSONDecodeError as e:
                print(f"[Warning] line {i+1} parse error: {e}")
                continue
    return data

from collections import defaultdict

def group_by_prompt(data):
    prompt_groups = defaultdict(list)
    for item in data:
        prompt_groups[item["prompt"]].append(item)
    return list(prompt_groups.values())

raw_data = extract_data(DATA_PATH)

grouped_data = group_by_prompt(raw_data)

def paginate_prompt_groups(groups, page_size):
    pages = []
    current_page = []
    current_count = 0

    for group in groups:
        if current_count + len(group) > page_size and current_page:
            pages.append(current_page)
            current_page = []
            current_count = 0
        current_page.extend(group)
        current_count += len(group)
    if current_page:
        pages.append(current_page)
    return pages

paginated_data = paginate_prompt_groups(grouped_data, PAGE_SIZE)
TOTAL_PAGES = len(paginated_data)

@app.get("/", response_class=HTMLResponse)
async def read_root(request: Request, page: int = 1):
    page = max(1, min(page, TOTAL_PAGES))
    page_data = paginated_data[page - 1]

    return templates.TemplateResponse("index.html", {
        "request": request,
        "page_data": page_data,
        "current_page": page,
        "total_pages": TOTAL_PAGES
    })


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("preview_data:app", host="127.0.0.1", port=8233, reload=True)